### ISSUE TITLE
Does this package replace custom hook definition for getting values from snapshot in body of the components(not render)

### ISSUE THREAD

**Issue by mahmutyilmazcs** [dai-shi/valtio-signal#5]
Hi, sorry for submitting an issue for this but I couldn't see a wiki page to ask.

I just use valtio with react and I have some problems with using values from snapshot in function body(not render). I just want to reach a value from store and use it as a dependency for some functions. If I use the following `const {value} = useSnapshot(store)`, it gets rendered twice. But It only triggered when an external render is triggered. (some state change in the same component that I used the code I mentioned) (When I used profiler to see why it rendered, it shows that useSyncExternalStore hook is updated) To workaround it I have this hook 
```
function useSnapshotValue(store, fieldName) {
    const [value, setValue] = useState(store[fieldName]);

    useEffect(() => {
        const unsubscribe = subscribe(store, fieldName, (newValue) => {
            setValue(newValue);
        });
        return unsubscribe;
    }, []);

    return value;
}
```

Does this package simply provides a general utility to replace this hook or something else or, don't I need this custom hook in the first place? 

And what you mean by this line in the readme. 

> To use Valtio proxy state, the official method is useSnapshot. One could create a custom hook with subscribe, snapshot and useState. 

Thanks in advance.

**Comment by dai-shi** [comment]
> Hi, sorry for submitting an issue for this but I couldn't see a wiki page to ask.

This is the right place to ask about valtio-signal.

> I just use valtio with react and I have some problems with using values from snapshot in function body(not render).

In function body, you should not use snapshot, just directly read from store.
`eslint-plugin-valtio` might help to catch that kind of misusages.

> I just want to reach a value from store and use it as a dependency for some functions.

A dependency, not in react hooks (like useCallback), correct?

> If I use the following `const {value} = useSnapshot(store)`, it gets rendered twice.

Really? Aren't you using StrictMode? Needs a minimal repro to dig into it.

> ```
> function useSnapshotValue(store, fieldName) {
>     const [value, setValue] = useState(store[fieldName]);
> 
>     useEffect(() => {
>         const unsubscribe = subscribe(store, fieldName, (newValue) => {
>             setValue(newValue);
>         });
>         return unsubscribe;
>     }, []);
> 
>     return value;
> }
> ```

That's almost a good one, expect I'd use `snapshot()` to cover various cases:
```js
function useSnapshotValue(store, fieldName) {
  const [value, setValue] = useState(() => snapshot(store)[fieldName]);
  useEffect(() => {
    const callback = () => setValue(snapshot(store)[fieldName]);
    const unsubscribe = subscribe(store, callback);
    callback();
    return unsubscribe;
  }, [store, fieldName]);
  return value;
}
```
It also includes various fixes.

> Does this package simply provides a general utility to replace this hook or something else or, don't I need this custom hook in the first place?

This package provides a very different syntax from hooks.
And, it's still brand new.
Any issues you see should probably be solvable with useSnapshot, unless you are hitting the gotchas: https://github.com/pmndrs/valtio/wiki/Some-gotchas

> And what you mean by this line in the readme.
> 
> > To use Valtio proxy state, the official method is useSnapshot. One could create a custom hook with subscribe, snapshot and useState.

It means something like the hook I just showed above, for instance.

**Comment by dai-shi** [comment]
valtio useSnapshot is the notion of using properties, and the properties used are called "affected".
In the -object component, nothing is affected. Thus, changing `a` property doesn't trigger re-render.
In the -primitive component, `.primitive` is affected. So, changing it triggers re-render.

I'm not sure about the double render. This seems working with/without StrictMode: https://codesandbox.io/s/strange-fermat-iy5yr6?file=/src/index.js
You might want to dig it deeper.

**Comment by dai-shi** [comment]
> > And what you mean by this line in the readme.
> > > To use Valtio proxy state, the official method is useSnapshot. One could create a custom hook with subscribe, snapshot and useState.
> 
> It means something like the hook I just showed above, for instance.

And, here comes a new library.
https://github.com/dai-shi/use-valtio
It's experimental.

**Comment by mahmutyilmazcs** [comment]
> I'm not sure about the double render. This seems working with/without StrictMode: https://codesandbox.io/s/strange-fermat-iy5yr6?file=/src/index.js
You might want to dig it deeper.
You mean there could be a bug in valtio? Then, I can try to debug it maybe. I was thinking I am doing something wrong until now.

**Comment by dai-shi** [comment]
No. I mean the simple sandbox I made works as expected. So, I assume there's no bugs.
But, yours doesn't. I don't know why. You want to find the difference. There can be a bug somewhere.

**Comment by mahmutyilmazcs** [comment]
I see. I guess I found the difference. My custom hook uses value as a useEffect dependency and this means registering two getters(one for in the original component while passing as a function parameter to my hook and the other one is in the useEffect dependency list in the hook). Therefore valtio notifies me twice. I confirm that removing from the useEffect dependency list decreased the render count to 1. 
However, when I moved the body of my hook to the component directly, valtio understands that snapshot.primitive is called from the same component and triggers render only once.

Then how can I make my hook listen and act according to the change without causing a double render? (And it can't read directly from state because it does not know about the state of the field name)

Sorry If I am bothering you too much but I've tried many different approaches for 2 days and I'm lost.

**Comment by dai-shi** [comment]
Can you make a small modification in https://codesandbox.io/s/strange-fermat-iy5yr6?file=/src/App.js ?

**Comment by mahmutyilmazcs** [comment]
[Here](https://codesandbox.io/s/gifted-yonath-d727lh)
Ofc, in the hook there is a state change and this triggers a new render. I want this;
- the original component shouldn't listen snapshot.count changes but myHook should.

**Comment by dai-shi** [comment]
Okay, so it's not a bug.
Here's something you might want.
https://codesandbox.io/s/exciting-pare-hz1cwr?file=/src/hook.js
